# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arnislielturks/playground/Urho3D-Project-Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arnislielturks/playground/Urho3D-Project-Template/ProjectTemplate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arnislielturks/playground/Urho3D-Project-Template/ProjectTemplate/CMakeFiles /Users/arnislielturks/playground/Urho3D-Project-Template/ProjectTemplate//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arnislielturks/playground/Urho3D-Project-Template/ProjectTemplate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjectTemplate

# Build rule for target.
ProjectTemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjectTemplate
.PHONY : ProjectTemplate

# fast build rule for target.
ProjectTemplate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/build
.PHONY : ProjectTemplate/fast

Source/AndroidEvents/NSObject.o: Source/AndroidEvents/NSObject.mm.o

.PHONY : Source/AndroidEvents/NSObject.o

# target to build an object file
Source/AndroidEvents/NSObject.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/NSObject.mm.o
.PHONY : Source/AndroidEvents/NSObject.mm.o

Source/AndroidEvents/NSObject.i: Source/AndroidEvents/NSObject.mm.i

.PHONY : Source/AndroidEvents/NSObject.i

# target to preprocess a source file
Source/AndroidEvents/NSObject.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/NSObject.mm.i
.PHONY : Source/AndroidEvents/NSObject.mm.i

Source/AndroidEvents/NSObject.s: Source/AndroidEvents/NSObject.mm.s

.PHONY : Source/AndroidEvents/NSObject.s

# target to generate assembly for a file
Source/AndroidEvents/NSObject.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/NSObject.mm.s
.PHONY : Source/AndroidEvents/NSObject.mm.s

Source/AndroidEvents/ServiceCmd.o: Source/AndroidEvents/ServiceCmd.cpp.o

.PHONY : Source/AndroidEvents/ServiceCmd.o

# target to build an object file
Source/AndroidEvents/ServiceCmd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/ServiceCmd.cpp.o
.PHONY : Source/AndroidEvents/ServiceCmd.cpp.o

Source/AndroidEvents/ServiceCmd.i: Source/AndroidEvents/ServiceCmd.cpp.i

.PHONY : Source/AndroidEvents/ServiceCmd.i

# target to preprocess a source file
Source/AndroidEvents/ServiceCmd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/ServiceCmd.cpp.i
.PHONY : Source/AndroidEvents/ServiceCmd.cpp.i

Source/AndroidEvents/ServiceCmd.s: Source/AndroidEvents/ServiceCmd.cpp.s

.PHONY : Source/AndroidEvents/ServiceCmd.s

# target to generate assembly for a file
Source/AndroidEvents/ServiceCmd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/ServiceCmd.cpp.s
.PHONY : Source/AndroidEvents/ServiceCmd.cpp.s

Source/AndroidEvents/Wrapper.o: Source/AndroidEvents/Wrapper.m.o

.PHONY : Source/AndroidEvents/Wrapper.o

# target to build an object file
Source/AndroidEvents/Wrapper.m.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/Wrapper.m.o
.PHONY : Source/AndroidEvents/Wrapper.m.o

Source/AndroidEvents/Wrapper.i: Source/AndroidEvents/Wrapper.m.i

.PHONY : Source/AndroidEvents/Wrapper.i

# target to preprocess a source file
Source/AndroidEvents/Wrapper.m.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/Wrapper.m.i
.PHONY : Source/AndroidEvents/Wrapper.m.i

Source/AndroidEvents/Wrapper.s: Source/AndroidEvents/Wrapper.m.s

.PHONY : Source/AndroidEvents/Wrapper.s

# target to generate assembly for a file
Source/AndroidEvents/Wrapper.m.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/AndroidEvents/Wrapper.m.s
.PHONY : Source/AndroidEvents/Wrapper.m.s

Source/Audio/AudioManager.o: Source/Audio/AudioManager.cpp.o

.PHONY : Source/Audio/AudioManager.o

# target to build an object file
Source/Audio/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Audio/AudioManager.cpp.o
.PHONY : Source/Audio/AudioManager.cpp.o

Source/Audio/AudioManager.i: Source/Audio/AudioManager.cpp.i

.PHONY : Source/Audio/AudioManager.i

# target to preprocess a source file
Source/Audio/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Audio/AudioManager.cpp.i
.PHONY : Source/Audio/AudioManager.cpp.i

Source/Audio/AudioManager.s: Source/Audio/AudioManager.cpp.s

.PHONY : Source/Audio/AudioManager.s

# target to generate assembly for a file
Source/Audio/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Audio/AudioManager.cpp.s
.PHONY : Source/Audio/AudioManager.cpp.s

Source/BaseApplication.o: Source/BaseApplication.cpp.o

.PHONY : Source/BaseApplication.o

# target to build an object file
Source/BaseApplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BaseApplication.cpp.o
.PHONY : Source/BaseApplication.cpp.o

Source/BaseApplication.i: Source/BaseApplication.cpp.i

.PHONY : Source/BaseApplication.i

# target to preprocess a source file
Source/BaseApplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BaseApplication.cpp.i
.PHONY : Source/BaseApplication.cpp.i

Source/BaseApplication.s: Source/BaseApplication.cpp.s

.PHONY : Source/BaseApplication.s

# target to generate assembly for a file
Source/BaseApplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BaseApplication.cpp.s
.PHONY : Source/BaseApplication.cpp.s

Source/BaseLevel.o: Source/BaseLevel.cpp.o

.PHONY : Source/BaseLevel.o

# target to build an object file
Source/BaseLevel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BaseLevel.cpp.o
.PHONY : Source/BaseLevel.cpp.o

Source/BaseLevel.i: Source/BaseLevel.cpp.i

.PHONY : Source/BaseLevel.i

# target to preprocess a source file
Source/BaseLevel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BaseLevel.cpp.i
.PHONY : Source/BaseLevel.cpp.i

Source/BaseLevel.s: Source/BaseLevel.cpp.s

.PHONY : Source/BaseLevel.s

# target to generate assembly for a file
Source/BaseLevel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BaseLevel.cpp.s
.PHONY : Source/BaseLevel.cpp.s

Source/BehaviourTree/BehaviourTree.o: Source/BehaviourTree/BehaviourTree.cpp.o

.PHONY : Source/BehaviourTree/BehaviourTree.o

# target to build an object file
Source/BehaviourTree/BehaviourTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BehaviourTree/BehaviourTree.cpp.o
.PHONY : Source/BehaviourTree/BehaviourTree.cpp.o

Source/BehaviourTree/BehaviourTree.i: Source/BehaviourTree/BehaviourTree.cpp.i

.PHONY : Source/BehaviourTree/BehaviourTree.i

# target to preprocess a source file
Source/BehaviourTree/BehaviourTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BehaviourTree/BehaviourTree.cpp.i
.PHONY : Source/BehaviourTree/BehaviourTree.cpp.i

Source/BehaviourTree/BehaviourTree.s: Source/BehaviourTree/BehaviourTree.cpp.s

.PHONY : Source/BehaviourTree/BehaviourTree.s

# target to generate assembly for a file
Source/BehaviourTree/BehaviourTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/BehaviourTree/BehaviourTree.cpp.s
.PHONY : Source/BehaviourTree/BehaviourTree.cpp.s

Source/Config/ConfigFile.o: Source/Config/ConfigFile.cpp.o

.PHONY : Source/Config/ConfigFile.o

# target to build an object file
Source/Config/ConfigFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Config/ConfigFile.cpp.o
.PHONY : Source/Config/ConfigFile.cpp.o

Source/Config/ConfigFile.i: Source/Config/ConfigFile.cpp.i

.PHONY : Source/Config/ConfigFile.i

# target to preprocess a source file
Source/Config/ConfigFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Config/ConfigFile.cpp.i
.PHONY : Source/Config/ConfigFile.cpp.i

Source/Config/ConfigFile.s: Source/Config/ConfigFile.cpp.s

.PHONY : Source/Config/ConfigFile.s

# target to generate assembly for a file
Source/Config/ConfigFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Config/ConfigFile.cpp.s
.PHONY : Source/Config/ConfigFile.cpp.s

Source/Config/ConfigManager.o: Source/Config/ConfigManager.cpp.o

.PHONY : Source/Config/ConfigManager.o

# target to build an object file
Source/Config/ConfigManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Config/ConfigManager.cpp.o
.PHONY : Source/Config/ConfigManager.cpp.o

Source/Config/ConfigManager.i: Source/Config/ConfigManager.cpp.i

.PHONY : Source/Config/ConfigManager.i

# target to preprocess a source file
Source/Config/ConfigManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Config/ConfigManager.cpp.i
.PHONY : Source/Config/ConfigManager.cpp.i

Source/Config/ConfigManager.s: Source/Config/ConfigManager.cpp.s

.PHONY : Source/Config/ConfigManager.s

# target to generate assembly for a file
Source/Config/ConfigManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Config/ConfigManager.cpp.s
.PHONY : Source/Config/ConfigManager.cpp.s

Source/Console/ConsoleHandler.o: Source/Console/ConsoleHandler.cpp.o

.PHONY : Source/Console/ConsoleHandler.o

# target to build an object file
Source/Console/ConsoleHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Console/ConsoleHandler.cpp.o
.PHONY : Source/Console/ConsoleHandler.cpp.o

Source/Console/ConsoleHandler.i: Source/Console/ConsoleHandler.cpp.i

.PHONY : Source/Console/ConsoleHandler.i

# target to preprocess a source file
Source/Console/ConsoleHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Console/ConsoleHandler.cpp.i
.PHONY : Source/Console/ConsoleHandler.cpp.i

Source/Console/ConsoleHandler.s: Source/Console/ConsoleHandler.cpp.s

.PHONY : Source/Console/ConsoleHandler.s

# target to generate assembly for a file
Source/Console/ConsoleHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Console/ConsoleHandler.cpp.s
.PHONY : Source/Console/ConsoleHandler.cpp.s

Source/Generator/Generator.o: Source/Generator/Generator.cpp.o

.PHONY : Source/Generator/Generator.o

# target to build an object file
Source/Generator/Generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Generator/Generator.cpp.o
.PHONY : Source/Generator/Generator.cpp.o

Source/Generator/Generator.i: Source/Generator/Generator.cpp.i

.PHONY : Source/Generator/Generator.i

# target to preprocess a source file
Source/Generator/Generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Generator/Generator.cpp.i
.PHONY : Source/Generator/Generator.cpp.i

Source/Generator/Generator.s: Source/Generator/Generator.cpp.s

.PHONY : Source/Generator/Generator.s

# target to generate assembly for a file
Source/Generator/Generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Generator/Generator.cpp.s
.PHONY : Source/Generator/Generator.cpp.s

Source/Generator/SimplexNoise.o: Source/Generator/SimplexNoise.cpp.o

.PHONY : Source/Generator/SimplexNoise.o

# target to build an object file
Source/Generator/SimplexNoise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Generator/SimplexNoise.cpp.o
.PHONY : Source/Generator/SimplexNoise.cpp.o

Source/Generator/SimplexNoise.i: Source/Generator/SimplexNoise.cpp.i

.PHONY : Source/Generator/SimplexNoise.i

# target to preprocess a source file
Source/Generator/SimplexNoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Generator/SimplexNoise.cpp.i
.PHONY : Source/Generator/SimplexNoise.cpp.i

Source/Generator/SimplexNoise.s: Source/Generator/SimplexNoise.cpp.s

.PHONY : Source/Generator/SimplexNoise.s

# target to generate assembly for a file
Source/Generator/SimplexNoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Generator/SimplexNoise.cpp.s
.PHONY : Source/Generator/SimplexNoise.cpp.s

Source/Input/ControllerInput.o: Source/Input/ControllerInput.cpp.o

.PHONY : Source/Input/ControllerInput.o

# target to build an object file
Source/Input/ControllerInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/ControllerInput.cpp.o
.PHONY : Source/Input/ControllerInput.cpp.o

Source/Input/ControllerInput.i: Source/Input/ControllerInput.cpp.i

.PHONY : Source/Input/ControllerInput.i

# target to preprocess a source file
Source/Input/ControllerInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/ControllerInput.cpp.i
.PHONY : Source/Input/ControllerInput.cpp.i

Source/Input/ControllerInput.s: Source/Input/ControllerInput.cpp.s

.PHONY : Source/Input/ControllerInput.s

# target to generate assembly for a file
Source/Input/ControllerInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/ControllerInput.cpp.s
.PHONY : Source/Input/ControllerInput.cpp.s

Source/Input/Controllers/JoystickInput.o: Source/Input/Controllers/JoystickInput.cpp.o

.PHONY : Source/Input/Controllers/JoystickInput.o

# target to build an object file
Source/Input/Controllers/JoystickInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/JoystickInput.cpp.o
.PHONY : Source/Input/Controllers/JoystickInput.cpp.o

Source/Input/Controllers/JoystickInput.i: Source/Input/Controllers/JoystickInput.cpp.i

.PHONY : Source/Input/Controllers/JoystickInput.i

# target to preprocess a source file
Source/Input/Controllers/JoystickInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/JoystickInput.cpp.i
.PHONY : Source/Input/Controllers/JoystickInput.cpp.i

Source/Input/Controllers/JoystickInput.s: Source/Input/Controllers/JoystickInput.cpp.s

.PHONY : Source/Input/Controllers/JoystickInput.s

# target to generate assembly for a file
Source/Input/Controllers/JoystickInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/JoystickInput.cpp.s
.PHONY : Source/Input/Controllers/JoystickInput.cpp.s

Source/Input/Controllers/KeyboardInput.o: Source/Input/Controllers/KeyboardInput.cpp.o

.PHONY : Source/Input/Controllers/KeyboardInput.o

# target to build an object file
Source/Input/Controllers/KeyboardInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/KeyboardInput.cpp.o
.PHONY : Source/Input/Controllers/KeyboardInput.cpp.o

Source/Input/Controllers/KeyboardInput.i: Source/Input/Controllers/KeyboardInput.cpp.i

.PHONY : Source/Input/Controllers/KeyboardInput.i

# target to preprocess a source file
Source/Input/Controllers/KeyboardInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/KeyboardInput.cpp.i
.PHONY : Source/Input/Controllers/KeyboardInput.cpp.i

Source/Input/Controllers/KeyboardInput.s: Source/Input/Controllers/KeyboardInput.cpp.s

.PHONY : Source/Input/Controllers/KeyboardInput.s

# target to generate assembly for a file
Source/Input/Controllers/KeyboardInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/KeyboardInput.cpp.s
.PHONY : Source/Input/Controllers/KeyboardInput.cpp.s

Source/Input/Controllers/MouseInput.o: Source/Input/Controllers/MouseInput.cpp.o

.PHONY : Source/Input/Controllers/MouseInput.o

# target to build an object file
Source/Input/Controllers/MouseInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/MouseInput.cpp.o
.PHONY : Source/Input/Controllers/MouseInput.cpp.o

Source/Input/Controllers/MouseInput.i: Source/Input/Controllers/MouseInput.cpp.i

.PHONY : Source/Input/Controllers/MouseInput.i

# target to preprocess a source file
Source/Input/Controllers/MouseInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/MouseInput.cpp.i
.PHONY : Source/Input/Controllers/MouseInput.cpp.i

Source/Input/Controllers/MouseInput.s: Source/Input/Controllers/MouseInput.cpp.s

.PHONY : Source/Input/Controllers/MouseInput.s

# target to generate assembly for a file
Source/Input/Controllers/MouseInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/MouseInput.cpp.s
.PHONY : Source/Input/Controllers/MouseInput.cpp.s

Source/Input/Controllers/ScreenJoystickInput.o: Source/Input/Controllers/ScreenJoystickInput.cpp.o

.PHONY : Source/Input/Controllers/ScreenJoystickInput.o

# target to build an object file
Source/Input/Controllers/ScreenJoystickInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/ScreenJoystickInput.cpp.o
.PHONY : Source/Input/Controllers/ScreenJoystickInput.cpp.o

Source/Input/Controllers/ScreenJoystickInput.i: Source/Input/Controllers/ScreenJoystickInput.cpp.i

.PHONY : Source/Input/Controllers/ScreenJoystickInput.i

# target to preprocess a source file
Source/Input/Controllers/ScreenJoystickInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/ScreenJoystickInput.cpp.i
.PHONY : Source/Input/Controllers/ScreenJoystickInput.cpp.i

Source/Input/Controllers/ScreenJoystickInput.s: Source/Input/Controllers/ScreenJoystickInput.cpp.s

.PHONY : Source/Input/Controllers/ScreenJoystickInput.s

# target to generate assembly for a file
Source/Input/Controllers/ScreenJoystickInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Input/Controllers/ScreenJoystickInput.cpp.s
.PHONY : Source/Input/Controllers/ScreenJoystickInput.cpp.s

Source/LevelManager.o: Source/LevelManager.cpp.o

.PHONY : Source/LevelManager.o

# target to build an object file
Source/LevelManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/LevelManager.cpp.o
.PHONY : Source/LevelManager.cpp.o

Source/LevelManager.i: Source/LevelManager.cpp.i

.PHONY : Source/LevelManager.i

# target to preprocess a source file
Source/LevelManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/LevelManager.cpp.i
.PHONY : Source/LevelManager.cpp.i

Source/LevelManager.s: Source/LevelManager.cpp.s

.PHONY : Source/LevelManager.s

# target to generate assembly for a file
Source/LevelManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/LevelManager.cpp.s
.PHONY : Source/LevelManager.cpp.s

Source/Levels/Credits.o: Source/Levels/Credits.cpp.o

.PHONY : Source/Levels/Credits.o

# target to build an object file
Source/Levels/Credits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Credits.cpp.o
.PHONY : Source/Levels/Credits.cpp.o

Source/Levels/Credits.i: Source/Levels/Credits.cpp.i

.PHONY : Source/Levels/Credits.i

# target to preprocess a source file
Source/Levels/Credits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Credits.cpp.i
.PHONY : Source/Levels/Credits.cpp.i

Source/Levels/Credits.s: Source/Levels/Credits.cpp.s

.PHONY : Source/Levels/Credits.s

# target to generate assembly for a file
Source/Levels/Credits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Credits.cpp.s
.PHONY : Source/Levels/Credits.cpp.s

Source/Levels/ExitGame.o: Source/Levels/ExitGame.cpp.o

.PHONY : Source/Levels/ExitGame.o

# target to build an object file
Source/Levels/ExitGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/ExitGame.cpp.o
.PHONY : Source/Levels/ExitGame.cpp.o

Source/Levels/ExitGame.i: Source/Levels/ExitGame.cpp.i

.PHONY : Source/Levels/ExitGame.i

# target to preprocess a source file
Source/Levels/ExitGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/ExitGame.cpp.i
.PHONY : Source/Levels/ExitGame.cpp.i

Source/Levels/ExitGame.s: Source/Levels/ExitGame.cpp.s

.PHONY : Source/Levels/ExitGame.s

# target to generate assembly for a file
Source/Levels/ExitGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/ExitGame.cpp.s
.PHONY : Source/Levels/ExitGame.cpp.s

Source/Levels/Level.o: Source/Levels/Level.cpp.o

.PHONY : Source/Levels/Level.o

# target to build an object file
Source/Levels/Level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Level.cpp.o
.PHONY : Source/Levels/Level.cpp.o

Source/Levels/Level.i: Source/Levels/Level.cpp.i

.PHONY : Source/Levels/Level.i

# target to preprocess a source file
Source/Levels/Level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Level.cpp.i
.PHONY : Source/Levels/Level.cpp.i

Source/Levels/Level.s: Source/Levels/Level.cpp.s

.PHONY : Source/Levels/Level.s

# target to generate assembly for a file
Source/Levels/Level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Level.cpp.s
.PHONY : Source/Levels/Level.cpp.s

Source/Levels/Loading.o: Source/Levels/Loading.cpp.o

.PHONY : Source/Levels/Loading.o

# target to build an object file
Source/Levels/Loading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Loading.cpp.o
.PHONY : Source/Levels/Loading.cpp.o

Source/Levels/Loading.i: Source/Levels/Loading.cpp.i

.PHONY : Source/Levels/Loading.i

# target to preprocess a source file
Source/Levels/Loading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Loading.cpp.i
.PHONY : Source/Levels/Loading.cpp.i

Source/Levels/Loading.s: Source/Levels/Loading.cpp.s

.PHONY : Source/Levels/Loading.s

# target to generate assembly for a file
Source/Levels/Loading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Loading.cpp.s
.PHONY : Source/Levels/Loading.cpp.s

Source/Levels/MainMenu.o: Source/Levels/MainMenu.cpp.o

.PHONY : Source/Levels/MainMenu.o

# target to build an object file
Source/Levels/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/MainMenu.cpp.o
.PHONY : Source/Levels/MainMenu.cpp.o

Source/Levels/MainMenu.i: Source/Levels/MainMenu.cpp.i

.PHONY : Source/Levels/MainMenu.i

# target to preprocess a source file
Source/Levels/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/MainMenu.cpp.i
.PHONY : Source/Levels/MainMenu.cpp.i

Source/Levels/MainMenu.s: Source/Levels/MainMenu.cpp.s

.PHONY : Source/Levels/MainMenu.s

# target to generate assembly for a file
Source/Levels/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/MainMenu.cpp.s
.PHONY : Source/Levels/MainMenu.cpp.s

Source/Levels/Splash.o: Source/Levels/Splash.cpp.o

.PHONY : Source/Levels/Splash.o

# target to build an object file
Source/Levels/Splash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Splash.cpp.o
.PHONY : Source/Levels/Splash.cpp.o

Source/Levels/Splash.i: Source/Levels/Splash.cpp.i

.PHONY : Source/Levels/Splash.i

# target to preprocess a source file
Source/Levels/Splash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Splash.cpp.i
.PHONY : Source/Levels/Splash.cpp.i

Source/Levels/Splash.s: Source/Levels/Splash.cpp.s

.PHONY : Source/Levels/Splash.s

# target to generate assembly for a file
Source/Levels/Splash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Splash.cpp.s
.PHONY : Source/Levels/Splash.cpp.s

Source/Levels/Voxel/Chunk.o: Source/Levels/Voxel/Chunk.cpp.o

.PHONY : Source/Levels/Voxel/Chunk.o

# target to build an object file
Source/Levels/Voxel/Chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/Chunk.cpp.o
.PHONY : Source/Levels/Voxel/Chunk.cpp.o

Source/Levels/Voxel/Chunk.i: Source/Levels/Voxel/Chunk.cpp.i

.PHONY : Source/Levels/Voxel/Chunk.i

# target to preprocess a source file
Source/Levels/Voxel/Chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/Chunk.cpp.i
.PHONY : Source/Levels/Voxel/Chunk.cpp.i

Source/Levels/Voxel/Chunk.s: Source/Levels/Voxel/Chunk.cpp.s

.PHONY : Source/Levels/Voxel/Chunk.s

# target to generate assembly for a file
Source/Levels/Voxel/Chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/Chunk.cpp.s
.PHONY : Source/Levels/Voxel/Chunk.cpp.s

Source/Levels/Voxel/ChunkGenerator.o: Source/Levels/Voxel/ChunkGenerator.cpp.o

.PHONY : Source/Levels/Voxel/ChunkGenerator.o

# target to build an object file
Source/Levels/Voxel/ChunkGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/ChunkGenerator.cpp.o
.PHONY : Source/Levels/Voxel/ChunkGenerator.cpp.o

Source/Levels/Voxel/ChunkGenerator.i: Source/Levels/Voxel/ChunkGenerator.cpp.i

.PHONY : Source/Levels/Voxel/ChunkGenerator.i

# target to preprocess a source file
Source/Levels/Voxel/ChunkGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/ChunkGenerator.cpp.i
.PHONY : Source/Levels/Voxel/ChunkGenerator.cpp.i

Source/Levels/Voxel/ChunkGenerator.s: Source/Levels/Voxel/ChunkGenerator.cpp.s

.PHONY : Source/Levels/Voxel/ChunkGenerator.s

# target to generate assembly for a file
Source/Levels/Voxel/ChunkGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/ChunkGenerator.cpp.s
.PHONY : Source/Levels/Voxel/ChunkGenerator.cpp.s

Source/Levels/Voxel/ChunkMesh.o: Source/Levels/Voxel/ChunkMesh.cpp.o

.PHONY : Source/Levels/Voxel/ChunkMesh.o

# target to build an object file
Source/Levels/Voxel/ChunkMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/ChunkMesh.cpp.o
.PHONY : Source/Levels/Voxel/ChunkMesh.cpp.o

Source/Levels/Voxel/ChunkMesh.i: Source/Levels/Voxel/ChunkMesh.cpp.i

.PHONY : Source/Levels/Voxel/ChunkMesh.i

# target to preprocess a source file
Source/Levels/Voxel/ChunkMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/ChunkMesh.cpp.i
.PHONY : Source/Levels/Voxel/ChunkMesh.cpp.i

Source/Levels/Voxel/ChunkMesh.s: Source/Levels/Voxel/ChunkMesh.cpp.s

.PHONY : Source/Levels/Voxel/ChunkMesh.s

# target to generate assembly for a file
Source/Levels/Voxel/ChunkMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/ChunkMesh.cpp.s
.PHONY : Source/Levels/Voxel/ChunkMesh.cpp.s

Source/Levels/Voxel/LightManager.o: Source/Levels/Voxel/LightManager.cpp.o

.PHONY : Source/Levels/Voxel/LightManager.o

# target to build an object file
Source/Levels/Voxel/LightManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/LightManager.cpp.o
.PHONY : Source/Levels/Voxel/LightManager.cpp.o

Source/Levels/Voxel/LightManager.i: Source/Levels/Voxel/LightManager.cpp.i

.PHONY : Source/Levels/Voxel/LightManager.i

# target to preprocess a source file
Source/Levels/Voxel/LightManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/LightManager.cpp.i
.PHONY : Source/Levels/Voxel/LightManager.cpp.i

Source/Levels/Voxel/LightManager.s: Source/Levels/Voxel/LightManager.cpp.s

.PHONY : Source/Levels/Voxel/LightManager.s

# target to generate assembly for a file
Source/Levels/Voxel/LightManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/LightManager.cpp.s
.PHONY : Source/Levels/Voxel/LightManager.cpp.s

Source/Levels/Voxel/TreeGenerator.o: Source/Levels/Voxel/TreeGenerator.cpp.o

.PHONY : Source/Levels/Voxel/TreeGenerator.o

# target to build an object file
Source/Levels/Voxel/TreeGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/TreeGenerator.cpp.o
.PHONY : Source/Levels/Voxel/TreeGenerator.cpp.o

Source/Levels/Voxel/TreeGenerator.i: Source/Levels/Voxel/TreeGenerator.cpp.i

.PHONY : Source/Levels/Voxel/TreeGenerator.i

# target to preprocess a source file
Source/Levels/Voxel/TreeGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/TreeGenerator.cpp.i
.PHONY : Source/Levels/Voxel/TreeGenerator.cpp.i

Source/Levels/Voxel/TreeGenerator.s: Source/Levels/Voxel/TreeGenerator.cpp.s

.PHONY : Source/Levels/Voxel/TreeGenerator.s

# target to generate assembly for a file
Source/Levels/Voxel/TreeGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/TreeGenerator.cpp.s
.PHONY : Source/Levels/Voxel/TreeGenerator.cpp.s

Source/Levels/Voxel/VoxelWorld.o: Source/Levels/Voxel/VoxelWorld.cpp.o

.PHONY : Source/Levels/Voxel/VoxelWorld.o

# target to build an object file
Source/Levels/Voxel/VoxelWorld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/VoxelWorld.cpp.o
.PHONY : Source/Levels/Voxel/VoxelWorld.cpp.o

Source/Levels/Voxel/VoxelWorld.i: Source/Levels/Voxel/VoxelWorld.cpp.i

.PHONY : Source/Levels/Voxel/VoxelWorld.i

# target to preprocess a source file
Source/Levels/Voxel/VoxelWorld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/VoxelWorld.cpp.i
.PHONY : Source/Levels/Voxel/VoxelWorld.cpp.i

Source/Levels/Voxel/VoxelWorld.s: Source/Levels/Voxel/VoxelWorld.cpp.s

.PHONY : Source/Levels/Voxel/VoxelWorld.s

# target to generate assembly for a file
Source/Levels/Voxel/VoxelWorld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Levels/Voxel/VoxelWorld.cpp.s
.PHONY : Source/Levels/Voxel/VoxelWorld.cpp.s

Source/Messages/Achievements.o: Source/Messages/Achievements.cpp.o

.PHONY : Source/Messages/Achievements.o

# target to build an object file
Source/Messages/Achievements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/Achievements.cpp.o
.PHONY : Source/Messages/Achievements.cpp.o

Source/Messages/Achievements.i: Source/Messages/Achievements.cpp.i

.PHONY : Source/Messages/Achievements.i

# target to preprocess a source file
Source/Messages/Achievements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/Achievements.cpp.i
.PHONY : Source/Messages/Achievements.cpp.i

Source/Messages/Achievements.s: Source/Messages/Achievements.cpp.s

.PHONY : Source/Messages/Achievements.s

# target to generate assembly for a file
Source/Messages/Achievements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/Achievements.cpp.s
.PHONY : Source/Messages/Achievements.cpp.s

Source/Messages/Notifications.o: Source/Messages/Notifications.cpp.o

.PHONY : Source/Messages/Notifications.o

# target to build an object file
Source/Messages/Notifications.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/Notifications.cpp.o
.PHONY : Source/Messages/Notifications.cpp.o

Source/Messages/Notifications.i: Source/Messages/Notifications.cpp.i

.PHONY : Source/Messages/Notifications.i

# target to preprocess a source file
Source/Messages/Notifications.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/Notifications.cpp.i
.PHONY : Source/Messages/Notifications.cpp.i

Source/Messages/Notifications.s: Source/Messages/Notifications.cpp.s

.PHONY : Source/Messages/Notifications.s

# target to generate assembly for a file
Source/Messages/Notifications.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/Notifications.cpp.s
.PHONY : Source/Messages/Notifications.cpp.s

Source/Messages/SingleAchievement.o: Source/Messages/SingleAchievement.cpp.o

.PHONY : Source/Messages/SingleAchievement.o

# target to build an object file
Source/Messages/SingleAchievement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/SingleAchievement.cpp.o
.PHONY : Source/Messages/SingleAchievement.cpp.o

Source/Messages/SingleAchievement.i: Source/Messages/SingleAchievement.cpp.i

.PHONY : Source/Messages/SingleAchievement.i

# target to preprocess a source file
Source/Messages/SingleAchievement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/SingleAchievement.cpp.i
.PHONY : Source/Messages/SingleAchievement.cpp.i

Source/Messages/SingleAchievement.s: Source/Messages/SingleAchievement.cpp.s

.PHONY : Source/Messages/SingleAchievement.s

# target to generate assembly for a file
Source/Messages/SingleAchievement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Messages/SingleAchievement.cpp.s
.PHONY : Source/Messages/SingleAchievement.cpp.s

Source/Mods/ModLoader.o: Source/Mods/ModLoader.cpp.o

.PHONY : Source/Mods/ModLoader.o

# target to build an object file
Source/Mods/ModLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Mods/ModLoader.cpp.o
.PHONY : Source/Mods/ModLoader.cpp.o

Source/Mods/ModLoader.i: Source/Mods/ModLoader.cpp.i

.PHONY : Source/Mods/ModLoader.i

# target to preprocess a source file
Source/Mods/ModLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Mods/ModLoader.cpp.i
.PHONY : Source/Mods/ModLoader.cpp.i

Source/Mods/ModLoader.s: Source/Mods/ModLoader.cpp.s

.PHONY : Source/Mods/ModLoader.s

# target to generate assembly for a file
Source/Mods/ModLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Mods/ModLoader.cpp.s
.PHONY : Source/Mods/ModLoader.cpp.s

Source/Nakama/NakamaManager.o: Source/Nakama/NakamaManager.cpp.o

.PHONY : Source/Nakama/NakamaManager.o

# target to build an object file
Source/Nakama/NakamaManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Nakama/NakamaManager.cpp.o
.PHONY : Source/Nakama/NakamaManager.cpp.o

Source/Nakama/NakamaManager.i: Source/Nakama/NakamaManager.cpp.i

.PHONY : Source/Nakama/NakamaManager.i

# target to preprocess a source file
Source/Nakama/NakamaManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Nakama/NakamaManager.cpp.i
.PHONY : Source/Nakama/NakamaManager.cpp.i

Source/Nakama/NakamaManager.s: Source/Nakama/NakamaManager.cpp.s

.PHONY : Source/Nakama/NakamaManager.s

# target to generate assembly for a file
Source/Nakama/NakamaManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Nakama/NakamaManager.cpp.s
.PHONY : Source/Nakama/NakamaManager.cpp.s

Source/Nakama/PacketHandler.o: Source/Nakama/PacketHandler.cpp.o

.PHONY : Source/Nakama/PacketHandler.o

# target to build an object file
Source/Nakama/PacketHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Nakama/PacketHandler.cpp.o
.PHONY : Source/Nakama/PacketHandler.cpp.o

Source/Nakama/PacketHandler.i: Source/Nakama/PacketHandler.cpp.i

.PHONY : Source/Nakama/PacketHandler.i

# target to preprocess a source file
Source/Nakama/PacketHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Nakama/PacketHandler.cpp.i
.PHONY : Source/Nakama/PacketHandler.cpp.i

Source/Nakama/PacketHandler.s: Source/Nakama/PacketHandler.cpp.s

.PHONY : Source/Nakama/PacketHandler.s

# target to generate assembly for a file
Source/Nakama/PacketHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Nakama/PacketHandler.cpp.s
.PHONY : Source/Nakama/PacketHandler.cpp.s

Source/PackageManager/PackageManager.o: Source/PackageManager/PackageManager.cpp.o

.PHONY : Source/PackageManager/PackageManager.o

# target to build an object file
Source/PackageManager/PackageManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/PackageManager/PackageManager.cpp.o
.PHONY : Source/PackageManager/PackageManager.cpp.o

Source/PackageManager/PackageManager.i: Source/PackageManager/PackageManager.cpp.i

.PHONY : Source/PackageManager/PackageManager.i

# target to preprocess a source file
Source/PackageManager/PackageManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/PackageManager/PackageManager.cpp.i
.PHONY : Source/PackageManager/PackageManager.cpp.i

Source/PackageManager/PackageManager.s: Source/PackageManager/PackageManager.cpp.s

.PHONY : Source/PackageManager/PackageManager.s

# target to generate assembly for a file
Source/PackageManager/PackageManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/PackageManager/PackageManager.cpp.s
.PHONY : Source/PackageManager/PackageManager.cpp.s

Source/Player/Player.o: Source/Player/Player.cpp.o

.PHONY : Source/Player/Player.o

# target to build an object file
Source/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Player/Player.cpp.o
.PHONY : Source/Player/Player.cpp.o

Source/Player/Player.i: Source/Player/Player.cpp.i

.PHONY : Source/Player/Player.i

# target to preprocess a source file
Source/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Player/Player.cpp.i
.PHONY : Source/Player/Player.cpp.i

Source/Player/Player.s: Source/Player/Player.cpp.s

.PHONY : Source/Player/Player.s

# target to generate assembly for a file
Source/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Player/Player.cpp.s
.PHONY : Source/Player/Player.cpp.s

Source/Player/PlayerState.o: Source/Player/PlayerState.cpp.o

.PHONY : Source/Player/PlayerState.o

# target to build an object file
Source/Player/PlayerState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Player/PlayerState.cpp.o
.PHONY : Source/Player/PlayerState.cpp.o

Source/Player/PlayerState.i: Source/Player/PlayerState.cpp.i

.PHONY : Source/Player/PlayerState.i

# target to preprocess a source file
Source/Player/PlayerState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Player/PlayerState.cpp.i
.PHONY : Source/Player/PlayerState.cpp.i

Source/Player/PlayerState.s: Source/Player/PlayerState.cpp.s

.PHONY : Source/Player/PlayerState.s

# target to generate assembly for a file
Source/Player/PlayerState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/Player/PlayerState.cpp.s
.PHONY : Source/Player/PlayerState.cpp.s

Source/SceneManager.o: Source/SceneManager.cpp.o

.PHONY : Source/SceneManager.o

# target to build an object file
Source/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/SceneManager.cpp.o
.PHONY : Source/SceneManager.cpp.o

Source/SceneManager.i: Source/SceneManager.cpp.i

.PHONY : Source/SceneManager.i

# target to preprocess a source file
Source/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/SceneManager.cpp.i
.PHONY : Source/SceneManager.cpp.i

Source/SceneManager.s: Source/SceneManager.cpp.s

.PHONY : Source/SceneManager.s

# target to generate assembly for a file
Source/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/SceneManager.cpp.s
.PHONY : Source/SceneManager.cpp.s

Source/State/State.o: Source/State/State.cpp.o

.PHONY : Source/State/State.o

# target to build an object file
Source/State/State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/State/State.cpp.o
.PHONY : Source/State/State.cpp.o

Source/State/State.i: Source/State/State.cpp.i

.PHONY : Source/State/State.i

# target to preprocess a source file
Source/State/State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/State/State.cpp.i
.PHONY : Source/State/State.cpp.i

Source/State/State.s: Source/State/State.cpp.s

.PHONY : Source/State/State.s

# target to generate assembly for a file
Source/State/State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/State/State.cpp.s
.PHONY : Source/State/State.cpp.s

Source/UI/Achievements/AchievementsWindow.o: Source/UI/Achievements/AchievementsWindow.cpp.o

.PHONY : Source/UI/Achievements/AchievementsWindow.o

# target to build an object file
Source/UI/Achievements/AchievementsWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Achievements/AchievementsWindow.cpp.o
.PHONY : Source/UI/Achievements/AchievementsWindow.cpp.o

Source/UI/Achievements/AchievementsWindow.i: Source/UI/Achievements/AchievementsWindow.cpp.i

.PHONY : Source/UI/Achievements/AchievementsWindow.i

# target to preprocess a source file
Source/UI/Achievements/AchievementsWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Achievements/AchievementsWindow.cpp.i
.PHONY : Source/UI/Achievements/AchievementsWindow.cpp.i

Source/UI/Achievements/AchievementsWindow.s: Source/UI/Achievements/AchievementsWindow.cpp.s

.PHONY : Source/UI/Achievements/AchievementsWindow.s

# target to generate assembly for a file
Source/UI/Achievements/AchievementsWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Achievements/AchievementsWindow.cpp.s
.PHONY : Source/UI/Achievements/AchievementsWindow.cpp.s

Source/UI/BaseWindow.o: Source/UI/BaseWindow.cpp.o

.PHONY : Source/UI/BaseWindow.o

# target to build an object file
Source/UI/BaseWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/BaseWindow.cpp.o
.PHONY : Source/UI/BaseWindow.cpp.o

Source/UI/BaseWindow.i: Source/UI/BaseWindow.cpp.i

.PHONY : Source/UI/BaseWindow.i

# target to preprocess a source file
Source/UI/BaseWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/BaseWindow.cpp.i
.PHONY : Source/UI/BaseWindow.cpp.i

Source/UI/BaseWindow.s: Source/UI/BaseWindow.cpp.s

.PHONY : Source/UI/BaseWindow.s

# target to generate assembly for a file
Source/UI/BaseWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/BaseWindow.cpp.s
.PHONY : Source/UI/BaseWindow.cpp.s

Source/UI/NewGameSettings/NewGameSettingsWindow.o: Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.o

.PHONY : Source/UI/NewGameSettings/NewGameSettingsWindow.o

# target to build an object file
Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.o
.PHONY : Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.o

Source/UI/NewGameSettings/NewGameSettingsWindow.i: Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.i

.PHONY : Source/UI/NewGameSettings/NewGameSettingsWindow.i

# target to preprocess a source file
Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.i
.PHONY : Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.i

Source/UI/NewGameSettings/NewGameSettingsWindow.s: Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.s

.PHONY : Source/UI/NewGameSettings/NewGameSettingsWindow.s

# target to generate assembly for a file
Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.s
.PHONY : Source/UI/NewGameSettings/NewGameSettingsWindow.cpp.s

Source/UI/Pause/PauseWindow.o: Source/UI/Pause/PauseWindow.cpp.o

.PHONY : Source/UI/Pause/PauseWindow.o

# target to build an object file
Source/UI/Pause/PauseWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Pause/PauseWindow.cpp.o
.PHONY : Source/UI/Pause/PauseWindow.cpp.o

Source/UI/Pause/PauseWindow.i: Source/UI/Pause/PauseWindow.cpp.i

.PHONY : Source/UI/Pause/PauseWindow.i

# target to preprocess a source file
Source/UI/Pause/PauseWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Pause/PauseWindow.cpp.i
.PHONY : Source/UI/Pause/PauseWindow.cpp.i

Source/UI/Pause/PauseWindow.s: Source/UI/Pause/PauseWindow.cpp.s

.PHONY : Source/UI/Pause/PauseWindow.s

# target to generate assembly for a file
Source/UI/Pause/PauseWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Pause/PauseWindow.cpp.s
.PHONY : Source/UI/Pause/PauseWindow.cpp.s

Source/UI/PopupMessage/PopupMessageWindow.o: Source/UI/PopupMessage/PopupMessageWindow.cpp.o

.PHONY : Source/UI/PopupMessage/PopupMessageWindow.o

# target to build an object file
Source/UI/PopupMessage/PopupMessageWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/PopupMessage/PopupMessageWindow.cpp.o
.PHONY : Source/UI/PopupMessage/PopupMessageWindow.cpp.o

Source/UI/PopupMessage/PopupMessageWindow.i: Source/UI/PopupMessage/PopupMessageWindow.cpp.i

.PHONY : Source/UI/PopupMessage/PopupMessageWindow.i

# target to preprocess a source file
Source/UI/PopupMessage/PopupMessageWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/PopupMessage/PopupMessageWindow.cpp.i
.PHONY : Source/UI/PopupMessage/PopupMessageWindow.cpp.i

Source/UI/PopupMessage/PopupMessageWindow.s: Source/UI/PopupMessage/PopupMessageWindow.cpp.s

.PHONY : Source/UI/PopupMessage/PopupMessageWindow.s

# target to generate assembly for a file
Source/UI/PopupMessage/PopupMessageWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/PopupMessage/PopupMessageWindow.cpp.s
.PHONY : Source/UI/PopupMessage/PopupMessageWindow.cpp.s

Source/UI/QuitConfirmation/QuitConfirmationWindow.o: Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.o

.PHONY : Source/UI/QuitConfirmation/QuitConfirmationWindow.o

# target to build an object file
Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.o
.PHONY : Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.o

Source/UI/QuitConfirmation/QuitConfirmationWindow.i: Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.i

.PHONY : Source/UI/QuitConfirmation/QuitConfirmationWindow.i

# target to preprocess a source file
Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.i
.PHONY : Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.i

Source/UI/QuitConfirmation/QuitConfirmationWindow.s: Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.s

.PHONY : Source/UI/QuitConfirmation/QuitConfirmationWindow.s

# target to generate assembly for a file
Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.s
.PHONY : Source/UI/QuitConfirmation/QuitConfirmationWindow.cpp.s

Source/UI/Scoreboard/ScoreboardWindow.o: Source/UI/Scoreboard/ScoreboardWindow.cpp.o

.PHONY : Source/UI/Scoreboard/ScoreboardWindow.o

# target to build an object file
Source/UI/Scoreboard/ScoreboardWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Scoreboard/ScoreboardWindow.cpp.o
.PHONY : Source/UI/Scoreboard/ScoreboardWindow.cpp.o

Source/UI/Scoreboard/ScoreboardWindow.i: Source/UI/Scoreboard/ScoreboardWindow.cpp.i

.PHONY : Source/UI/Scoreboard/ScoreboardWindow.i

# target to preprocess a source file
Source/UI/Scoreboard/ScoreboardWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Scoreboard/ScoreboardWindow.cpp.i
.PHONY : Source/UI/Scoreboard/ScoreboardWindow.cpp.i

Source/UI/Scoreboard/ScoreboardWindow.s: Source/UI/Scoreboard/ScoreboardWindow.cpp.s

.PHONY : Source/UI/Scoreboard/ScoreboardWindow.s

# target to generate assembly for a file
Source/UI/Scoreboard/ScoreboardWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Scoreboard/ScoreboardWindow.cpp.s
.PHONY : Source/UI/Scoreboard/ScoreboardWindow.cpp.s

Source/UI/Settings/SettingsWindow.o: Source/UI/Settings/SettingsWindow.cpp.o

.PHONY : Source/UI/Settings/SettingsWindow.o

# target to build an object file
Source/UI/Settings/SettingsWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Settings/SettingsWindow.cpp.o
.PHONY : Source/UI/Settings/SettingsWindow.cpp.o

Source/UI/Settings/SettingsWindow.i: Source/UI/Settings/SettingsWindow.cpp.i

.PHONY : Source/UI/Settings/SettingsWindow.i

# target to preprocess a source file
Source/UI/Settings/SettingsWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Settings/SettingsWindow.cpp.i
.PHONY : Source/UI/Settings/SettingsWindow.cpp.i

Source/UI/Settings/SettingsWindow.s: Source/UI/Settings/SettingsWindow.cpp.s

.PHONY : Source/UI/Settings/SettingsWindow.s

# target to generate assembly for a file
Source/UI/Settings/SettingsWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Settings/SettingsWindow.cpp.s
.PHONY : Source/UI/Settings/SettingsWindow.cpp.s

Source/UI/Settings/UIOption.o: Source/UI/Settings/UIOption.cpp.o

.PHONY : Source/UI/Settings/UIOption.o

# target to build an object file
Source/UI/Settings/UIOption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Settings/UIOption.cpp.o
.PHONY : Source/UI/Settings/UIOption.cpp.o

Source/UI/Settings/UIOption.i: Source/UI/Settings/UIOption.cpp.i

.PHONY : Source/UI/Settings/UIOption.i

# target to preprocess a source file
Source/UI/Settings/UIOption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Settings/UIOption.cpp.i
.PHONY : Source/UI/Settings/UIOption.cpp.i

Source/UI/Settings/UIOption.s: Source/UI/Settings/UIOption.cpp.s

.PHONY : Source/UI/Settings/UIOption.s

# target to generate assembly for a file
Source/UI/Settings/UIOption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/Settings/UIOption.cpp.s
.PHONY : Source/UI/Settings/UIOption.cpp.s

Source/UI/WindowManager.o: Source/UI/WindowManager.cpp.o

.PHONY : Source/UI/WindowManager.o

# target to build an object file
Source/UI/WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/WindowManager.cpp.o
.PHONY : Source/UI/WindowManager.cpp.o

Source/UI/WindowManager.i: Source/UI/WindowManager.cpp.i

.PHONY : Source/UI/WindowManager.i

# target to preprocess a source file
Source/UI/WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/WindowManager.cpp.i
.PHONY : Source/UI/WindowManager.cpp.i

Source/UI/WindowManager.s: Source/UI/WindowManager.cpp.s

.PHONY : Source/UI/WindowManager.s

# target to generate assembly for a file
Source/UI/WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjectTemplate.dir/build.make CMakeFiles/ProjectTemplate.dir/Source/UI/WindowManager.cpp.s
.PHONY : Source/UI/WindowManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ProjectTemplate"
	@echo "... Source/AndroidEvents/NSObject.o"
	@echo "... Source/AndroidEvents/NSObject.i"
	@echo "... Source/AndroidEvents/NSObject.s"
	@echo "... Source/AndroidEvents/ServiceCmd.o"
	@echo "... Source/AndroidEvents/ServiceCmd.i"
	@echo "... Source/AndroidEvents/ServiceCmd.s"
	@echo "... Source/AndroidEvents/Wrapper.o"
	@echo "... Source/AndroidEvents/Wrapper.i"
	@echo "... Source/AndroidEvents/Wrapper.s"
	@echo "... Source/Audio/AudioManager.o"
	@echo "... Source/Audio/AudioManager.i"
	@echo "... Source/Audio/AudioManager.s"
	@echo "... Source/BaseApplication.o"
	@echo "... Source/BaseApplication.i"
	@echo "... Source/BaseApplication.s"
	@echo "... Source/BaseLevel.o"
	@echo "... Source/BaseLevel.i"
	@echo "... Source/BaseLevel.s"
	@echo "... Source/BehaviourTree/BehaviourTree.o"
	@echo "... Source/BehaviourTree/BehaviourTree.i"
	@echo "... Source/BehaviourTree/BehaviourTree.s"
	@echo "... Source/Config/ConfigFile.o"
	@echo "... Source/Config/ConfigFile.i"
	@echo "... Source/Config/ConfigFile.s"
	@echo "... Source/Config/ConfigManager.o"
	@echo "... Source/Config/ConfigManager.i"
	@echo "... Source/Config/ConfigManager.s"
	@echo "... Source/Console/ConsoleHandler.o"
	@echo "... Source/Console/ConsoleHandler.i"
	@echo "... Source/Console/ConsoleHandler.s"
	@echo "... Source/Generator/Generator.o"
	@echo "... Source/Generator/Generator.i"
	@echo "... Source/Generator/Generator.s"
	@echo "... Source/Generator/SimplexNoise.o"
	@echo "... Source/Generator/SimplexNoise.i"
	@echo "... Source/Generator/SimplexNoise.s"
	@echo "... Source/Input/ControllerInput.o"
	@echo "... Source/Input/ControllerInput.i"
	@echo "... Source/Input/ControllerInput.s"
	@echo "... Source/Input/Controllers/JoystickInput.o"
	@echo "... Source/Input/Controllers/JoystickInput.i"
	@echo "... Source/Input/Controllers/JoystickInput.s"
	@echo "... Source/Input/Controllers/KeyboardInput.o"
	@echo "... Source/Input/Controllers/KeyboardInput.i"
	@echo "... Source/Input/Controllers/KeyboardInput.s"
	@echo "... Source/Input/Controllers/MouseInput.o"
	@echo "... Source/Input/Controllers/MouseInput.i"
	@echo "... Source/Input/Controllers/MouseInput.s"
	@echo "... Source/Input/Controllers/ScreenJoystickInput.o"
	@echo "... Source/Input/Controllers/ScreenJoystickInput.i"
	@echo "... Source/Input/Controllers/ScreenJoystickInput.s"
	@echo "... Source/LevelManager.o"
	@echo "... Source/LevelManager.i"
	@echo "... Source/LevelManager.s"
	@echo "... Source/Levels/Credits.o"
	@echo "... Source/Levels/Credits.i"
	@echo "... Source/Levels/Credits.s"
	@echo "... Source/Levels/ExitGame.o"
	@echo "... Source/Levels/ExitGame.i"
	@echo "... Source/Levels/ExitGame.s"
	@echo "... Source/Levels/Level.o"
	@echo "... Source/Levels/Level.i"
	@echo "... Source/Levels/Level.s"
	@echo "... Source/Levels/Loading.o"
	@echo "... Source/Levels/Loading.i"
	@echo "... Source/Levels/Loading.s"
	@echo "... Source/Levels/MainMenu.o"
	@echo "... Source/Levels/MainMenu.i"
	@echo "... Source/Levels/MainMenu.s"
	@echo "... Source/Levels/Splash.o"
	@echo "... Source/Levels/Splash.i"
	@echo "... Source/Levels/Splash.s"
	@echo "... Source/Levels/Voxel/Chunk.o"
	@echo "... Source/Levels/Voxel/Chunk.i"
	@echo "... Source/Levels/Voxel/Chunk.s"
	@echo "... Source/Levels/Voxel/ChunkGenerator.o"
	@echo "... Source/Levels/Voxel/ChunkGenerator.i"
	@echo "... Source/Levels/Voxel/ChunkGenerator.s"
	@echo "... Source/Levels/Voxel/ChunkMesh.o"
	@echo "... Source/Levels/Voxel/ChunkMesh.i"
	@echo "... Source/Levels/Voxel/ChunkMesh.s"
	@echo "... Source/Levels/Voxel/LightManager.o"
	@echo "... Source/Levels/Voxel/LightManager.i"
	@echo "... Source/Levels/Voxel/LightManager.s"
	@echo "... Source/Levels/Voxel/TreeGenerator.o"
	@echo "... Source/Levels/Voxel/TreeGenerator.i"
	@echo "... Source/Levels/Voxel/TreeGenerator.s"
	@echo "... Source/Levels/Voxel/VoxelWorld.o"
	@echo "... Source/Levels/Voxel/VoxelWorld.i"
	@echo "... Source/Levels/Voxel/VoxelWorld.s"
	@echo "... Source/Messages/Achievements.o"
	@echo "... Source/Messages/Achievements.i"
	@echo "... Source/Messages/Achievements.s"
	@echo "... Source/Messages/Notifications.o"
	@echo "... Source/Messages/Notifications.i"
	@echo "... Source/Messages/Notifications.s"
	@echo "... Source/Messages/SingleAchievement.o"
	@echo "... Source/Messages/SingleAchievement.i"
	@echo "... Source/Messages/SingleAchievement.s"
	@echo "... Source/Mods/ModLoader.o"
	@echo "... Source/Mods/ModLoader.i"
	@echo "... Source/Mods/ModLoader.s"
	@echo "... Source/Nakama/NakamaManager.o"
	@echo "... Source/Nakama/NakamaManager.i"
	@echo "... Source/Nakama/NakamaManager.s"
	@echo "... Source/Nakama/PacketHandler.o"
	@echo "... Source/Nakama/PacketHandler.i"
	@echo "... Source/Nakama/PacketHandler.s"
	@echo "... Source/PackageManager/PackageManager.o"
	@echo "... Source/PackageManager/PackageManager.i"
	@echo "... Source/PackageManager/PackageManager.s"
	@echo "... Source/Player/Player.o"
	@echo "... Source/Player/Player.i"
	@echo "... Source/Player/Player.s"
	@echo "... Source/Player/PlayerState.o"
	@echo "... Source/Player/PlayerState.i"
	@echo "... Source/Player/PlayerState.s"
	@echo "... Source/SceneManager.o"
	@echo "... Source/SceneManager.i"
	@echo "... Source/SceneManager.s"
	@echo "... Source/State/State.o"
	@echo "... Source/State/State.i"
	@echo "... Source/State/State.s"
	@echo "... Source/UI/Achievements/AchievementsWindow.o"
	@echo "... Source/UI/Achievements/AchievementsWindow.i"
	@echo "... Source/UI/Achievements/AchievementsWindow.s"
	@echo "... Source/UI/BaseWindow.o"
	@echo "... Source/UI/BaseWindow.i"
	@echo "... Source/UI/BaseWindow.s"
	@echo "... Source/UI/NewGameSettings/NewGameSettingsWindow.o"
	@echo "... Source/UI/NewGameSettings/NewGameSettingsWindow.i"
	@echo "... Source/UI/NewGameSettings/NewGameSettingsWindow.s"
	@echo "... Source/UI/Pause/PauseWindow.o"
	@echo "... Source/UI/Pause/PauseWindow.i"
	@echo "... Source/UI/Pause/PauseWindow.s"
	@echo "... Source/UI/PopupMessage/PopupMessageWindow.o"
	@echo "... Source/UI/PopupMessage/PopupMessageWindow.i"
	@echo "... Source/UI/PopupMessage/PopupMessageWindow.s"
	@echo "... Source/UI/QuitConfirmation/QuitConfirmationWindow.o"
	@echo "... Source/UI/QuitConfirmation/QuitConfirmationWindow.i"
	@echo "... Source/UI/QuitConfirmation/QuitConfirmationWindow.s"
	@echo "... Source/UI/Scoreboard/ScoreboardWindow.o"
	@echo "... Source/UI/Scoreboard/ScoreboardWindow.i"
	@echo "... Source/UI/Scoreboard/ScoreboardWindow.s"
	@echo "... Source/UI/Settings/SettingsWindow.o"
	@echo "... Source/UI/Settings/SettingsWindow.i"
	@echo "... Source/UI/Settings/SettingsWindow.s"
	@echo "... Source/UI/Settings/UIOption.o"
	@echo "... Source/UI/Settings/UIOption.i"
	@echo "... Source/UI/Settings/UIOption.s"
	@echo "... Source/UI/WindowManager.o"
	@echo "... Source/UI/WindowManager.i"
	@echo "... Source/UI/WindowManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

